config/routes.rb
Rails.application.routes.draw do
  scope :module => 'datajam/datacard' do
    scope '/admin/plugins/datajam-datacard' do
      get '/install' => 'plugin#install'
      get '/uninstall' => 'plugin#uninstall'
      get '/refresh_assets' => 'plugin#refresh_assets'
    end
  end

  namespace :admin do
    resources :cards do
      post 'to_html', :on => :member
      post 'to_csv', :on => :member
    end
    resources :mapping_data
    resources :csv_data

    resources :data_sets do
      resources :cards, :only => [:index, :new, :create]
    end

    resources :mappings, :only => [:index, :show] do
      resource :mapping_settings, :only => [:edit, :update], :as => 'settings', :path => 'settings'
    end
  end
end

app/models/mapping_settings.rb
class MappingSettings
  include Mongoid::Document

  field :settings,   type: Hash, default: {}
  field :mapping_id, type: String
end

app/controllers/admin/mapping_settings_controller.rb
class Admin::MappingSettingsController < ::Datajam::Datacard::EngineController
  before_filter :find_mapping
  before_filter :find_mapping_settings

  def edit
  end

  def update
    if @mapping_settings.update_attributes(params[:mapping_settings])
      flash[:success] = "Settings updated."
      redirect_to admin_mappings_path
    else
      flash[:error] = @cards.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  private

  def find_mapping_settings
    @mapping_settings = @mapping.persisted_settings
  end
end

app/views/admin/mapping_settings/edit.html.erb
<h2><%= @mapping.name %> &rsaquo; Settings</h2>

<%= simple_form_for @mapping_settings, method: :put, url: admin_mapping_settings_path(@mapping.id), html: { class: "form-horizontal" } do |f| %>
  <h3>Settings</h3>
  <div class="settings">
    <%= f.fields_for :settings do |sf| %>
      <% @mapping.settings.values.each do |setting| %>
        <%= mapping_field_for sf, setting, @mapping_settings.settings[setting.name.to_s] %>
      <% end %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: "Save settings", class: "btn-primary" %>
    <%= link_to "Cancel", :back, class: "btn" %>
  </div>
<% end %>