config/routes.rb
Rails.application.routes.draw do
  scope :module => 'datajam/datacard' do
    scope '/admin/plugins/datajam-datacard' do
      get '/install' => 'plugin#install'
      get '/uninstall' => 'plugin#uninstall'
      get '/refresh_assets' => 'plugin#refresh_assets'
    end
  end

  namespace :admin do
    resources :cards do
      post 'to_html', :on => :member
      post 'to_csv', :on => :member
    end
    resources :mapping_data
    resources :csv_data

    resources :data_sets do
      resources :cards, :only => [:index, :new, :create]
    end

    resources :mappings, :only => [:index, :show] do
      resource :mapping_settings, :only => [:edit, :update], :as => 'settings', :path => 'settings'
    end
  end
end

app/controllers/admin/mappings_controller.rb
class Admin::MappingsController < ::Datajam::Datacard::EngineController
  before_filter :load_mappings, only: [:index]

  def index
  end
end

app/views/admin/mappings/_mapping.html.erb
<h4><%= mapping.name %>, v<%= mapping.version %></h4>
<p><%= link_to mapping.homepage %></p>
<p>
  <%= mapping.summary %>
  <% unless mapping.description.blank? %>
  <br>
  <%= mapping.description %>
  <% end -%>
</p>
<p><strong>Authors:</strong> <%= mapping.authors %>, <%= link_to "#{mapping.email}", "mailto:#{mapping.email}" %> </p>
<div class="controls">
  <p>
    <%= link_to "Edit Settings", edit_admin_mapping_settings_path(mapping), class: "btn" %>
  </p>
</div>
<div class="well">
  <%= simple_table_for mapping.endpoints.values, ["Endpoint", "Description", ""] do |endpoint| %>
  <tr>
    <td width="35%"><%= endpoint.label %></td>
    <td width="50%"><%= endpoint.help_text %></td>
    <td><%= link_to "New Card", new_admin_card_path(mapping_id: mapping.id, endpoint: endpoint.name, :from => :mapping), class: "btn btn-small btn-primary", method: "get" %></td>
  </tr>
  <% end -%>
</div>