config/routes.rb
Rails.application.routes.draw do
  scope :module => 'datajam/datacard' do
    scope '/admin/plugins/datajam-datacard' do
      get '/install' => 'plugin#install'
      get '/uninstall' => 'plugin#uninstall'
      get '/refresh_assets' => 'plugin#refresh_assets'
    end
  end

  namespace :admin do
    resources :cards do
      post 'to_html', :on => :member
      post 'to_csv', :on => :member
    end
    resources :mapping_data
    resources :csv_data

    resources :data_sets do
      resources :cards, :only => [:index, :new, :create]
    end

    resources :mappings, :only => [:index, :show] do
      resource :mapping_settings, :only => [:edit, :update], :as => 'settings', :path => 'settings'
    end
  end
end

app/controllers/admin/cards_controller.rb
require 'hashie/mash'

class Admin::CardsController < AdminController
  before_filter :find_or_initialize_card, :except => [:index, :create]
  before_filter :load_data_set, :only => [:new]
  before_filter :set_form_type, :except => [:index, :destroy, :detach]
  before_filter :load_mappings, :only => [:new, :edit]
  before_filter :prepare_mapping_params, :only => [:edit]

  def index
    @cards = DataCard.unscoped.all.order(:updated_at => :desc)
    @cards = DataCard.where(data_set_id: params[:data_set_id]) if params[:data_set_id].present?
    @cards = filter_and_sort @cards
    render_if_ajax 'admin/cards/_table'
  end

  def show
  end

  def new
    @card.data_set.sourced = "#{@from.to_s.titleize}Data".constantize.new if @card.data_set && @card.data_set.new_record?
  end

  def edit
  end

  def create
    @card = DataCard.new(params[:card])
    load_mappings
    if @card.has_siblings? && params[:update_data].nil? && @card.from_mapping?
      params[:card].delete(:data_set_attributes)
    end
    if @card.save
      flash[:success] = "Card saved."
      redirect_to admin_card_path(@card)
    else
      cascade_errors(@card, :data_set, :sourced)
      @mapping = @card.data_set.sourced.mapping rescue nil
      @endpoint = @card.data_set.sourced.endpoint rescue nil
      render 'new'
    end
  end

  def update
    params[:card].delete(:data_set_attributes) if params[:update_data].nil? && @card.from_mapping?
    if @card.update_attributes(params[:card])
      flash[:success] = "Card updated."
      redirect_to admin_card_path(@card)
    else
      cascade_errors(@card, :data_set, :sourced)
      @mapping = @card.data_set.sourced.mapping
      @endpoint = @card.data_set.sourced.endpoint
      render 'edit'
    end
  end

  def destroy
    if @card.data_set_id && !@card.has_siblings?
      success = @card.data_set.sourced.destroy
    else
      success = @card.destroy
    end
    if success
      flash[:success] = "Card deleted."
    else
      cascade_errors(@card, :data_set)
      redirect_to :back
    end
    redirect_to admin_cards_path
  end

  def to_csv
    sourced_id = @card.data_set.sourced.id
    @card.data_set.sourced = CsvData.new(data: @card.data_set.to_csv(@card.data_options), source: @card.source)
    if @card.data_set.save
      mapping = MappingData.find(sourced_id)
      mapping.set(:data_sets, [])
      mapping.destroy
      flash[:success] = "Card(s) converted to CSV."
      redirect_to edit_admin_card_path(@card)
    else
      cascade_errors(@card, :data_set, :sourced)
      redirect_to :back
    end
  end

  def to_html
    data_set = @card.data_set
    destroy_data_set = (data_set.cards.length <= 1)
    if @card.update_attributes(data_set: nil, display_type: :html)
      data_set.sourced.destroy if destroy_data_set
      flash[:success] = "Card(s) converted to HTML."
      redirect_to edit_admin_card_path(@card)
    else
      cascade_errors(@card, :data_set)
      redirect_to :back
    end
  end

  protected

  def find_or_initialize_card
    if params[:id].present?
      @card = DataCard.find(params[:id])
    else
      @card = DataCard.new
    end
  end

  def load_data_set
    return if @from == :html || (params[:from].present? && params[:from].to_sym == :html)
    @card.data_set ||= params[:data_set_id].present? ? DataSet.find(params[:data_set_id]) : DataSet.new
  end

  def set_form_type
    @from = :html
    if params[:from].present?
      @from = params[:from].to_sym
    elsif @card && (@card.data_set.persisted? rescue false)
      if @card.from_csv?
        @from = :csv
      elsif @card.from_mapping?
        @from = :mapping
      end
    end rescue nil
  end

  def load_mappings
    @mappings = Datajam::Datacard.mappings
    return unless @from == :mapping
    if @card.new_record?
      if @card.data_set && @card.data_set.persisted?
        @mapping ||= @card.data_set.sourced.mapping
        @endpoint ||= @card.data_set.sourced.endpoint
      elsif params[:mapping_id].present?
        @mapping ||= @mappings.find_by_klass(params[:mapping_id])
        @endpoint ||= @mapping.endpoints[params[:endpoint].to_sym]
      end
    else
      @mapping ||= @card.data_set.sourced.mapping rescue nil
      @endpoint ||= @mapping.endpoints[@card.data_set.sourced.endpoint_name] rescue nil
    end
  end

  def prepare_mapping_params
    return unless @card.from_mapping?
    @card.data_set.sourced.params = Hashie::Mash.new(@card.data_set.sourced.params)
  end

  def cascade_errors(*args)
    stack = args.first
    args[1..-1].each do |arg|
      pushed = stack.send arg
      if pushed.nil? || !pushed.errors.any?
        break
      else
        stack = pushed
      end
    end
    flash[:error] = stack.errors.full_messages.to_sentence
  end

end

app/views/admin/cards/_from_own_data_form.html.erb
<h3>From own data</h3>

<%= simple_form_for [:admin, @card], html: { class: "form-horizontal" } do |f| %>

  <%= f.input :title %>
  <%= f.input :tag_string, input_html: { class: "taggable" } %>

  <%= f.input :csv, as: :text, label: "Your data", input_html: { class: "datajamTemplate rawData", rows: 10, cols: 100 } %>
  <%= f.input :source, as: :text, label: 'Source Attribution', input_html: { rows: 5, cols: 80 }, hint: "Can use HTML" %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-primary submit" %>
    <%= button_tag "Preview", value: "1", name: "preview", class: "btn-small preview", target: "_blank" %>
  </div>
<% end %>

app/views/admin/cards/_mapping.erb
<h4><%= mapping.name %></h4>
<p><%= mapping.summary %></p>

<%= table_for mapping.endpoints.values, ["Name", "Title", "Path", ""] do |endpoint| %>
<tr>
  <td><%= endpoint.name %></td>
  <td><%= endpoint.title %></td>
  <td><%= endpoint.uri %></td>
  <td><%= link_to "Fetch Datacard", new_admin_mapping_request_path(mapping.id, endpoint.name), class: "btn btn-small", method: "get" %></td>
</tr>
<% end -%>

app/views/admin/cards/_navigation.html.erb
<ul class="nav nav-pills">
    <li class="<%= 'active' if @from.blank? && @mappings.blank? %>"><%= link_to "Card List", admin_cards_path %></li>
    <li class="dropdown <%= 'active' unless @from.blank? || @card.persisted? %>">
        <%= link_to "#",
            :class => 'dropdown-toggle',
            :'data-toggle' => 'dropdown' do %>
            Create New Card <b class="caret"></b>
        <% end %>
        <ul class="dropdown-menu">
            <li class="<%= 'active' if @from == :csv %>"><%= link_to "From CSV", new_admin_card_path(:from => :csv) %></li>
            <li class="<%= 'active' if @from == :html %>"><%= link_to "Enter plain HTML", new_admin_card_path(:from => :html) %></li>
            <li class="<%= 'active' if @from == :mapping %>"><%= link_to "From remote data", admin_mappings_path(:from => :mapping) %></li>
        </ul>
    </li>
</ul>

app/views/admin/cards/_shared_data_set_warning.html.erb
<% if @card.has_siblings? %>
    <div class="alert alert-warning">
        <p>This card is based on a shared data set! Any changes you make to the data here will reflect in this data set's other cards:</p>
        <ul>
            <% @card.siblings.each do |card| %>
            <li><%= link_to card.title, edit_admin_card_path(card) %></li>
            <% end %>
        </ul>
    </div>
<% end rescue nil %>

app/views/admin/cards/_table.html.erb
<%= search_box('title,csv,body,source,cached_tag_string') %>
<%= table_for @cards, [:title, :display_type, "Tags", :updated_at] do |card| %>
  <tr>
    <td><%= link_to card.title, edit_admin_card_path(card) %></td>
    <td><%= card.display_type %></td>
    <td><%= raw card.tag_string.split(',').join('<br>') %></td>
    <td><%= card.updated_at.to_s :humane %></td>
    <td>
      <% if card.data_set_id %>
      <%= button_to "Duplicate", new_admin_data_set_card_path(card.data_set_id), class: "btn btn-small btn-primary", method: "get" %>
      <% end %>
    </td>
    <td>
      <% if card.data_set_id %>
        <div class="btn-group">
          <a href="#" class="btn btn-small btn-warning dropdown-toggle" data-toggle="dropdown">
            Convert <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "HTML", to_html_admin_card_path(card), method: "post", confirm: "Are you sure? This will completely destroy the card's dataset." %></li>
            <% if card.from_mapping? %>
              <li><%= link_to "CSV", to_csv_admin_card_path(card), method: "post", confirm: "Are you sure? This is a one-way process, and will affect any other cards using this dataset." %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </td>
    <td><%= button_to "Preview", admin_card_path(card), class: "btn btn-small", method: "get" %></td>
    <td><%= delete_button admin_card_path(card), title: "This will completely destroy the card", confirm: "Are you sure? This will completely destroy the card." %></td>
  </tr>
<% end %>

app/views/admin/cards/edit.html.erb
<%= render :partial => 'shared_data_set_warning' %>
<h2>Editing Data Card: <%= @card.title %></h2>

<%= render :partial => 'navigation' %>

<div class="tab-content">
    <div class="tab-pane active" id="index">
        <% content_for :extra_fields do %>
        <div class="control-group string optional">
            <label for="card_update_data" class="string optional control-label">Update dataset</label>
            <div class="controls">
                <input type="checkbox" id="card_update_data" class="string optional" name="update_data" />
            </div>
        </div>
        <% end %>
        <%= render :partial => "admin/cards/forms/#{@from}" %>
    </div>
</div>

app/views/admin/cards/index.html.erb
<h2>Data Cards</h2>

<%= render :partial => 'navigation' %>

<div class="tab-content">
    <div class="tab-pane active" id="index">
        <%= render :partial => 'table' %>
    </div>
</div>

app/views/admin/cards/new.html.erb
<%= render :partial => 'shared_data_set_warning' %>
<h2>Data Cards</h2>

<%= render :partial => 'navigation' %>

<div class="tab-content">
    <div class="tab-pane active" id="index">
        <h2>New Card From <%= @from.to_s.titleize %></h2>
        <% content_for :extra_fields do %>
        <div class="control-group string optional">
            <label for="card_update_data" class="string optional control-label">Update dataset</label>
            <div class="controls">
                <input type="checkbox" id="card_update_data" class="string optional" name="update_data" />
            </div>
        </div>
        <% end if @card.has_siblings? %>
        <%= render :partial => "admin/cards/forms/#{@from}" %>
    </div>
</div>

app/views/admin/cards/show.html.erb
<h2>Data Card Preview</h2>
<%= render partial: 'navigation' %>

<%= raw @card.html %>

<div class="form-actions">
<%= link_to "Edit This Card", edit_admin_card_path(@card), class: "btn btn-primary"%>
<%= link_to "Back", :back, class: "btn" %>
</div>